[package]
name = "gnrt"
version = "0.0.0"
edition = "2021"

[lib]
name = "gnrt_lib"
path = "lib/lib.rs"

[[bin]]
name = "gnrt"
path = "main.rs"

[dependencies]
anyhow = "1"
cargo_metadata = "0.15"
cargo-platform = "0.1"
clap = {version = "4", features = ["derive"]}
handlebars = "4.3.7"
itertools = "0.12"
flate2 = "1"
reqwest = {version = "0.11", features = ["blocking"]}
log = { version = "0.4", features = ["std"] }
once_cell = "1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tar = "0.4"
tempfile = "3"
toml = "0.8"

[dependencies.env_logger]
version = "0.10"
default-features = false
features = ["color"]

# Patch `guppy` in a way that corresponds to
# https://github.com/guppy-rs/guppy/pull/453
# (and an already discussed follow-up, not-yet-raised PR
# for `host_links` and `target_links` accessors).
#
# TODO(https://crbug.com/395924069): Stop patching `guppy` after the upstream
# discussion of the PR concludes whether to 1) merge it as-is, or 2) tweak it.
[dependencies.guppy]
git = 'https://github.com/anforowicz/guppy.git'
branch = 'cargo-set-more-links-accessors'
[dependencies.target-spec]
git = 'https://github.com/anforowicz/guppy.git'
branch = 'cargo-set-more-links-accessors'
